Update Centos image to one that include OpenSSL 1.0.2
This OpenSSL version is necessary to install the new `nginx` version we're using now (`nginx-1.13.7-1.el7_4.ngx.x86_64`).

The error otherwise is:
```
Error: Package: 1:nginx-1.13.7-1.el7_4.ngx.x86_64 (/nginx-1.13.7-1.el7_4.ngx.x86_64)
Requires: libcrypto.so.10(OPENSSL_1.0.2)(64bit)
```